# Generated by Django 3.0.4 on 2020-03-17 07:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('money', models.IntegerField(default=0, verbose_name='金额')),
                ('genre', models.IntegerField(default=0, verbose_name='优惠券类型')),
                ('commodity_genre', models.IntegerField(default=0, verbose_name='支持优惠券的商品类型')),
                ('is_online', models.IntegerField(default=0, verbose_name='是否上线')),
                ('online_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='下线时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='OrderCommodityMapModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('order_id', models.IntegerField(default=0, verbose_name='订单id')),
                ('commodity_id', models.IntegerField(default=0, verbose_name='商品id')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('count', models.IntegerField(default=0, verbose_name='商品个数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单商品映射表',
                'db_table': 'order_commodity_map',
            },
        ),
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('order_id', models.IntegerField(default=0, verbose_name='订单id')),
                ('coupon_id', models.IntegerField(default=0, verbose_name='优惠券id')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单优惠券',
                'db_table': 'order_coupon',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('payment', models.IntegerField(default=0, verbose_name='付款')),
                ('amount', models.IntegerField(default=0, verbose_name='订单金额')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='discounts_price',
            field=models.IntegerField(default=0, verbose_name='优惠价格'),
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='genre',
            field=models.IntegerField(default=1, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='commoditymodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='commoditymodel',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
        ),
    ]
